# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 549))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.songTable = QtWidgets.QTableView(self.centralwidget)
        self.songTable.setEnabled(True)
        self.songTable.setMinimumSize(QtCore.QSize(400, 300))
        self.songTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.songTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.songTable.setSortingEnabled(True)
        self.songTable.setObjectName("songTable")
        self.songTable.verticalHeader().setMinimumSectionSize(100)
        self.horizontalLayout.addWidget(self.songTable)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.CreateButton = QtWidgets.QPushButton(self.centralwidget)
        self.CreateButton.setMinimumSize(QtCore.QSize(100, 0))
        self.CreateButton.setObjectName("CreateButton")
        self.verticalLayout_2.addWidget(self.CreateButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.EditButton = QtWidgets.QPushButton(self.centralwidget)
        self.EditButton.setMinimumSize(QtCore.QSize(100, 0))
        self.EditButton.setObjectName("EditButton")
        self.verticalLayout_2.addWidget(self.EditButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.DeleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.DeleteButton.setMinimumSize(QtCore.QSize(100, 0))
        self.DeleteButton.setObjectName("DeleteButton")
        self.verticalLayout_2.addWidget(self.DeleteButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveButton.setMinimumSize(QtCore.QSize(100, 0))
        self.SaveButton.setObjectName("SaveButton")
        self.verticalLayout_2.addWidget(self.SaveButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.SearchLabel = QtWidgets.QLabel(self.centralwidget)
        self.SearchLabel.setObjectName("SearchLabel")
        self.gridLayout.addWidget(self.SearchLabel, 0, 0, 1, 1)
        self.searchEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.searchEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.searchEdit.setObjectName("searchEdit")
        self.gridLayout.addWidget(self.searchEdit, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CreateButton.setText(_translate("MainWindow", "Создать"))
        self.EditButton.setText(_translate("MainWindow", "Редактировать"))
        self.DeleteButton.setText(_translate("MainWindow", "Удалить"))
        self.SaveButton.setText(_translate("MainWindow", "Сохранить"))
        self.SearchLabel.setText(_translate("MainWindow", "Поиск:"))
        self.searchEdit.setPlaceholderText(_translate("MainWindow", "Введите Название или Исполнителя"))
