# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'song_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(882, 600)
        Dialog.setMinimumSize(QtCore.QSize(800, 600))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.previewPathEdit = QtWidgets.QLineEdit(Dialog)
        self.previewPathEdit.setReadOnly(True)
        self.previewPathEdit.setObjectName("previewPathEdit")
        self.gridLayout.addWidget(self.previewPathEdit, 6, 2, 1, 1)
        self.ratingSpin = QtWidgets.QSpinBox(Dialog)
        self.ratingSpin.setMinimum(1)
        self.ratingSpin.setMaximum(5)
        self.ratingSpin.setDisplayIntegerBase(10)
        self.ratingSpin.setObjectName("ratingSpin")
        self.gridLayout.addWidget(self.ratingSpin, 8, 2, 1, 1)
        self.artistEdit = QtWidgets.QLineEdit(Dialog)
        self.artistEdit.setObjectName("artistEdit")
        self.gridLayout.addWidget(self.artistEdit, 2, 2, 1, 1)
        self.titleLabel = QtWidgets.QLabel(Dialog)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout.addWidget(self.titleLabel, 0, 0, 1, 1)
        self.browseButton = QtWidgets.QPushButton(Dialog)
        self.browseButton.setObjectName("browseButton")
        self.gridLayout.addWidget(self.browseButton, 6, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 5, 2, 1, 1)
        self.RatingLabel = QtWidgets.QLabel(Dialog)
        self.RatingLabel.setObjectName("RatingLabel")
        self.gridLayout.addWidget(self.RatingLabel, 8, 0, 1, 1)
        self.PreviewlLabel = QtWidgets.QLabel(Dialog)
        self.PreviewlLabel.setObjectName("PreviewlLabel")
        self.gridLayout.addWidget(self.PreviewlLabel, 6, 0, 1, 1)
        self.artistLabel = QtWidgets.QLabel(Dialog)
        self.artistLabel.setObjectName("artistLabel")
        self.gridLayout.addWidget(self.artistLabel, 2, 0, 1, 1)
        self.durationLabel = QtWidgets.QLabel(Dialog)
        self.durationLabel.setObjectName("durationLabel")
        self.gridLayout.addWidget(self.durationLabel, 4, 0, 1, 1)
        self.titleEdit = QtWidgets.QLineEdit(Dialog)
        self.titleEdit.setObjectName("titleEdit")
        self.gridLayout.addWidget(self.titleEdit, 0, 2, 1, 1)
        self.durationEdit = QtWidgets.QLineEdit(Dialog)
        self.durationEdit.setObjectName("durationEdit")
        self.gridLayout.addWidget(self.durationEdit, 4, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 7, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem5)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Создать/Редактировать"))
        self.titleLabel.setText(_translate("Dialog", "Название"))
        self.browseButton.setText(_translate("Dialog", "Загрузить"))
        self.RatingLabel.setText(_translate("Dialog", "Оценка"))
        self.PreviewlLabel.setText(_translate("Dialog", "Превью"))
        self.artistLabel.setText(_translate("Dialog", "Исполнитель"))
        self.durationLabel.setText(_translate("Dialog", "Продолжительность"))
        self.durationEdit.setInputMask(_translate("Dialog", "99:99", "mm:ss"))
