# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'song_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(882, 591)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(530, 550, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 861, 531))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.PreviewlLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.PreviewlLabel.setObjectName("PreviewlLabel")
        self.gridLayout.addWidget(self.PreviewlLabel, 3, 0, 1, 1)
        self.artistLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.artistLabel.setObjectName("artistLabel")
        self.gridLayout.addWidget(self.artistLabel, 1, 0, 1, 1)
        self.previewPathEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.previewPathEdit.setReadOnly(True)
        self.previewPathEdit.setObjectName("previewPathEdit")
        self.gridLayout.addWidget(self.previewPathEdit, 3, 2, 1, 1)
        self.durationLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.durationLabel.setObjectName("durationLabel")
        self.gridLayout.addWidget(self.durationLabel, 2, 0, 1, 1)
        self.titleLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout.addWidget(self.titleLabel, 0, 0, 1, 1)
        self.titleEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.titleEdit.setObjectName("titleEdit")
        self.gridLayout.addWidget(self.titleEdit, 0, 2, 1, 1)
        self.artistEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.artistEdit.setObjectName("artistEdit")
        self.gridLayout.addWidget(self.artistEdit, 1, 2, 1, 1)
        self.durationEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.durationEdit.setObjectName("durationEdit")
        self.gridLayout.addWidget(self.durationEdit, 2, 2, 1, 1)
        self.browseButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.browseButton.setObjectName("browseButton")
        self.gridLayout.addWidget(self.browseButton, 3, 3, 1, 1)
        self.RatingLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.RatingLabel.setObjectName("RatingLabel")
        self.gridLayout.addWidget(self.RatingLabel, 4, 0, 1, 1)
        self.ratingSpin = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.ratingSpin.setMinimum(1)
        self.ratingSpin.setMaximum(5)
        self.ratingSpin.setDisplayIntegerBase(10)
        self.ratingSpin.setObjectName("ratingSpin")
        self.gridLayout.addWidget(self.ratingSpin, 4, 2, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Создать/Редактировать"))
        self.PreviewlLabel.setText(_translate("Dialog", "Превью"))
        self.artistLabel.setText(_translate("Dialog", "Исполнитель"))
        self.durationLabel.setText(_translate("Dialog", "Продолжительность"))
        self.titleLabel.setText(_translate("Dialog", "Название"))
        self.durationEdit.setInputMask(_translate("Dialog", "99:99", "mm:ss"))
        self.browseButton.setText(_translate("Dialog", "Загрузить"))
        self.RatingLabel.setText(_translate("Dialog", "Оценка"))
